name: Update awesome-stars list
on:
  schedule:
    - cron: '38 17 * * 6'
jobs:
  awesome-stars:
    name: update-list
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade --upgrade-strategy eager --pre pip
        python3 -m pip install --upgrade-strategy eager --pre starred
    - name: update-readme
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: starred --username RogueScholar --repository awesome-stars --sort --token ${GITHUB_TOKEN} --message 'List updated by GitHub Actions'
      
